// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type OrderRequest struct {
	Id string `path:"id"`
}

type OrderResponse struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	UserName string `json:"userName"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
